export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_GROUP = "CREATE_GROUP";
export const GET_USERS_CHAT = "GET_USERS_CHAT";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_ERROR = "DELETE_CHAT_ERROR";